//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCoronaProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        public string Name { get; set; }
        public string LastName { get; set; }
        public int Id { get; set; }
        public string Phone { get; set; }
        public string CellPhone { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
    }
}
