//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCoronaProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccination
    {
        public System.DateTime GetVaccinated { get; set; }
        public string manufacturer { get; set; }
        public Nullable<int> Id { get; set; }
    }
}
